version: '3'

services:
  web:
    image: nginx:latest
    container_name: my-laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    links:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-laravel-app-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_HOST=database"
      - "DB_PORT=3306"
      - "DB_DATABASE=mydatabase"
      - "DB_USERNAME=mydatabaseuser"
      - "DB_PASSWORD=mypassword"

  database:
    image: mysql:5.7
    container_name: my-laravel-app-db
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=mydatabase"
      - "MYSQL_USER=mydatabaseuser"
      - "MYSQL_PASSWORD=mypassword"
      - "MYSQL_ROOT_PASSWORD=rootpassword"

volumes:
  dbdata:
